# Generated by Django 5.1.3 on 2024-12-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='static/assets/img/user.png', upload_to='static/assets/img'),
        ),
    ]
